# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Dan Belin
tagline:          'A Jekyll theme'
description:      ''
url:              https://dan-belin.github.io/
baseurl:          /

author:
  name:           'Daniel Belin'
  url:            https://twitter.com/dfbelin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dan-belin/dan-belin.github.io/
